"""Rename captainId to captain_id in Team model

Revision ID: 10c7a70fb6dd
Revises: a5067402abc6
Create Date: 2025-11-12 07:54:51.072267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c7a70fb6dd'
down_revision = 'a5067402abc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('captain_id', sa.UUID(), nullable=False))
    op.drop_constraint('fk_teams_captainId_users', 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teams_captain_id_users'), 'teams', 'users', ['captain_id'], ['id'])
    op.drop_column('teams', 'captainId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('captainId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_teams_captain_id_users'), 'teams', type_='foreignkey')
    op.create_foreign_key('fk_teams_captainId_users', 'teams', 'users', ['captainId'], ['id'])
    op.drop_column('teams', 'captain_id')
    # ### end Alembic commands ###
