'''Create sport table

Revision ID: 26136506f6f1
Revises: a14319821c8b
Create Date: 2025-11-17 09:18:37.638240

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26136506f6f1'
down_revision = 'a14319821c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport')
    # ### end Alembic commands ###
