"""Add TeamApplication model

Revision ID: 2fd756909650
Revises: 10c7a70fb6dd
Create Date: 2025-11-12 18:42:47.690881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fd756909650'
down_revision = '10c7a70fb6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_applications', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('team_applications', sa.Column('team_id', sa.UUID(), nullable=False))
    op.add_column('team_applications', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_unique_constraint('_user_team_uc', 'team_applications', ['user_id', 'team_id'])
    op.drop_constraint('fk_team_applications_teamId_teams', 'team_applications', type_='foreignkey')
    op.drop_constraint('fk_team_applications_userId_users', 'team_applications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_team_applications_user_id_users'), 'team_applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_team_applications_team_id_teams'), 'team_applications', 'teams', ['team_id'], ['id'])
    op.drop_column('team_applications', 'userId')
    op.drop_column('team_applications', 'teamId')
    op.drop_column('team_applications', 'status')
    op.drop_column('team_applications', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_applications', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('team_applications', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('team_applications', sa.Column('teamId', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('team_applications', sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_team_applications_team_id_teams'), 'team_applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_team_applications_user_id_users'), 'team_applications', type_='foreignkey')
    op.create_foreign_key('fk_team_applications_userId_users', 'team_applications', 'users', ['userId'], ['id'])
    op.create_foreign_key('fk_team_applications_teamId_teams', 'team_applications', 'teams', ['teamId'], ['id'])
    op.drop_constraint('_user_team_uc', 'team_applications', type_='unique')
    op.drop_column('team_applications', 'team_id')
    op.drop_column('team_applications', 'user_id')
    op.drop_column('team_applications', 'created_at')
    # ### end Alembic commands ###
