"""Make User fields nullable

Revision ID: 389ee9e5d4a1
Revises: 6a6dcd37c9bf
Create Date: 2025-11-14 12:06:00.061599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389ee9e5d4a1'
down_revision = '6a6dcd37c9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
