"""Add stats to PlayerProfile and elo to User

Revision ID: 400292b411bc
Revises: b7de70b2aaad
Create Date: 2025-11-09 05:55:22.099913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400292b411bc'
down_revision = 'b7de70b2aaad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mvpAwards', sa.Integer(), nullable=True))
        batch_op.drop_column('elo')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('elo')

    with op.batch_alter_table('player_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('mvpAwards')
        batch_op.drop_column('assists')
        batch_op.drop_column('goals')

    # ### end Alembic commands ###
