"""Add UserSession table

Revision ID: 433aa716fa09
Revises: fc93fb9c7ad5
Create Date: 2025-11-03 20:19:19.688419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433aa716fa09'
down_revision = 'fc93fb9c7ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('refreshTokenHash', sa.String(length=128), nullable=False),
    sa.Column('userAgent', sa.String(length=200), nullable=True),
    sa.Column('ipAddress', sa.String(length=45), nullable=True),
    sa.Column('lastActiveAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refreshTokenHash')
    )
    op.drop_column('user', 'refreshToken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refreshToken', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('user_session')
    # ### end Alembic commands ###
