
"""Add TeamApplication model and sport_id to Team

Revision ID: 5c04b91173c5
Revises: 70dcc3f59e29
Create Date: 2025-11-02 10:17:57.168331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c04b91173c5'
down_revision = '70dcc3f59e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('team', sa.Column('sport_id', sa.String(length=50), nullable=True))
    op.execute("UPDATE team SET sport_id = 'sport-1' WHERE sport_id IS NULL")
    op.alter_column('team', 'sport_id', nullable=False)
    op.create_foreign_key('fk_team_sport_id_sport', 'team', 'sport', ['sport_id'], ['id'])
    op.drop_column('team', 'game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('game', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('fk_team_sport_id_sport', 'team', type_='foreignkey')
    op.drop_column('team', 'sport_id')
    op.drop_table('team_application')
    # ### end Alembic commands ###
