"""Add avatar_url to User model

Revision ID: 6a6dcd37c9bf
Revises: 7ab1d2fd7772
Create Date: 2025-11-14 08:03:17.641703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6dcd37c9bf'
down_revision = '7ab1d2fd7772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_team_uc', 'subscriptions', ['user_id', 'team_id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_constraint('_user_team_uc', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
