"""Add description to Team model

Revision ID: 6d3fa08029f7
Revises: cdc5e8f37984
Create Date: 2025-11-15 21:38:51.354689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d3fa08029f7'
down_revision = 'cdc5e8f37984'
branch_labels = None
depends_on = None

notification_enum = postgresql.ENUM('FRIEND_REQUEST', 'FRIEND_ACCEPT', 'TEAM_INVITE', 'TEAM_ACCEPT', 'LFG_POST', name='notificationtype', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    notification_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('notifications', sa.Column('type', notification_enum, nullable=False))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.add_column('teams', sa.Column('description', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'description')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notifications', 'type')
    notification_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
