"""Add TeamSeasonStats and createdAt to Team

Revision ID: 70dcc3f59e29
Revises: 72fc06f1e9d4
Create Date: 2025-11-01 22:35:52.471359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dcc3f59e29'
down_revision = '72fc06f1e9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('leagueRank', sa.String(length=50), nullable=True),
    sa.Column('finalElo', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('team', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'createdAt')
    op.drop_table('team_season_stats')
    # ### end Alembic commands ###
