"""Add statistics fields to Team model

Revision ID: 72fc06f1e9d4
Revises: ab9c5c31d509
Create Date: 2025-11-01 22:15:04.729068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fc06f1e9d4'
down_revision = 'ab9c5c31d509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('leagueRank', sa.String(length=50), nullable=True))
    op.add_column('team', sa.Column('currentStreakType', sa.String(length=1), nullable=True))
    op.add_column('team', sa.Column('currentStreakCount', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('form', sa.String(length=5), nullable=True))
    op.add_column('team', sa.Column('mvpPlayerId', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('topScorerPlayerId', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('cleanSheets', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('avgRating', sa.Integer(), nullable=True))
    op.alter_column('team', 'logoUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_foreign_key(None, 'team', 'user', ['mvpPlayerId'], ['id'])
    op.create_foreign_key(None, 'team', 'user', ['topScorerPlayerId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.alter_column('team', 'logoUrl',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('team', 'avgRating')
    op.drop_column('team', 'cleanSheets')
    op.drop_column('team', 'topScorerPlayerId')
    op.drop_column('team', 'mvpPlayerId')
    op.drop_column('team', 'form')
    op.drop_column('team', 'currentStreakCount')
    op.drop_column('team', 'currentStreakType')
    op.drop_column('team', 'leagueRank')
    op.drop_column('team', 'losses')
    op.drop_column('team', 'wins')
    # ### end Alembic commands ###
