"""Change Team.id to UUID and related columns

Revision ID: 7ab1d2fd7772
Revises: eb882e4ea437
Create Date: 2025-11-13 11:36:07.687735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab1d2fd7772'
down_revision = 'eb882e4ea437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
