"""Add TeamApplication model

Revision ID: 7dbdf531d788
Revises: 5c04b91173c5
Create Date: 2025-11-02 19:25:11.226416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dbdf531d788'
down_revision = '5c04b91173c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_applications',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.drop_table('team_application')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_application_team_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='team_application_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_application_pkey')
    )
    op.drop_table('team_applications')
    # ### end Alembic commands ###
