"""Change user avatarUrl to Text

Revision ID: 920804208d98
Revises: e317311a2802
Create Date: 2025-10-31 18:36:08.552119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920804208d98'
down_revision = 'e317311a2802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sport_parentId_fkey'), 'sport', type_='foreignkey')
    op.drop_column('sport', 'parentId')
    op.alter_column('team', 'logoUrl',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('user', 'avatarUrl',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatarUrl',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('team', 'logoUrl',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.add_column('sport', sa.Column('parentId', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sport_parentId_fkey'), 'sport', 'sport', ['parentId'], ['id'])
    # ### end Alembic commands ###
