"""Make team logoUrl, game, and city nullable

Revision ID: a5067402abc6
Revises: 9f334b221f51
Create Date: 2025-11-12 07:51:32.796346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5067402abc6'
down_revision = '9f334b221f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'logoUrl',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('teams', 'game',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(op.f('uq_user_privacy_settings_user_id'), 'user_privacy_settings', ['user_id'])
    op.create_unique_constraint(op.f('uq_user_settings_user_id'), 'user_settings', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_settings_user_id'), 'user_settings', type_='unique')
    op.drop_constraint(op.f('uq_user_privacy_settings_user_id'), 'user_privacy_settings', type_='unique')
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('teams', 'game',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('teams', 'logoUrl',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
