"""Add password and refreshToken to User model

Revision ID: ab9c5c31d509
Revises: c3aa6c329875
Create Date: 2025-11-01 17:19:51.290160

"""
from alembic import op
import sqlalchemy as sa
import bcrypt


# revision identifiers, used by Alembic.
revision = 'ab9c5c31d509'
down_revision = 'c3aa6c329875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the password column, allowing nulls temporarily
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('refreshToken', sa.String(length=500), nullable=True))

    # Set a default password for existing users
    # This is a temporary measure for the migration to succeed.
    salt = bcrypt.gensalt()
    default_password_hash = bcrypt.hashpw(b'temporary_password', salt).decode('utf-8')
    
    # Use Alembic's recommended way to update data
    user_table = sa.table('user', sa.column('password', sa.String))
    op.execute(
        user_table.update().values(password=default_password_hash)
    )

    # Now, alter the column to be non-nullable
    op.alter_column('user', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refreshToken')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
