"""Add LfgPost model

Revision ID: b7de70b2aaad
Revises: 1b868e7916af
Create Date: 2025-11-08 23:12:42.054548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7de70b2aaad'
down_revision = '1b868e7916af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lfg_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('authorId', sa.UUID(), nullable=False),
    sa.Column('teamId', sa.UUID(), nullable=True),
    sa.Column('sportId', sa.String(), nullable=False),
    sa.Column('requiredRole', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sportId'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lfg_posts')
    # ### end Alembic commands ###
