"""Initial migration from scratch

Revision ID: bcc80b55f2f1
Revises: 
Create Date: 2025-11-08 16:47:28.513003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc80b55f2f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playground',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('surface', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('logoUrl', sa.String(length=200), nullable=True),
    sa.Column('contribution', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    sport_table = op.create_table('sport',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isTeamSport', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(sport_table,
        [
            {'id': 'sport-1', 'name': 'Футбол', 'isTeamSport': True},
            {'id': 'sport-2', 'name': 'Баскетбол', 'isTeamSport': True},
            {'id': 'sport-3', 'name': 'Волейбол', 'isTeamSport': True},
            {'id': 'sport-4', 'name': 'Хоккей', 'isTeamSport': True},
            {'id': 'sport-5', 'name': 'Гандбол', 'isTeamSport': True},
            {'id': 'sport-6', 'name': 'Регби', 'isTeamSport': True},
            {'id': 'sport-7', 'name': 'Водное поло', 'isTeamSport': True},
            {'id': 'sport-8', 'name': 'Лакросс', 'isTeamSport': True},
            {'id': 'sport-9', 'name': 'Флорбол', 'isTeamSport': True},
            {'id': 'sport-10', 'name': 'Хоккей на траве', 'isTeamSport': True},
            {'id': 'sport-11', 'name': 'Крикет', 'isTeamSport': True},
            {'id': 'sport-12', 'name': 'Бейсбол / Софтбол', 'isTeamSport': True},
            {'id': 'sport-13', 'name': 'Американский футбол', 'isTeamSport': True},
            {'id': 'sport-14', 'name': 'Корфбол', 'isTeamSport': True},
            {'id': 'sport-15', 'name': 'Нетбол', 'isTeamSport': True},
            {'id': 'sport-16', 'name': 'Сепак такро', 'isTeamSport': True},
            {'id': 'sport-17', 'name': 'Алтимат фрисби', 'isTeamSport': True},
            {'id': 'sport-18', 'name': 'Пейнтбол / Лазертаг', 'isTeamSport': True},
            {'id': 'sport-19', 'name': 'Киберспорт', 'isTeamSport': True},
            {'id': 'sport-20', 'name': 'Командные беговые эстафеты', 'isTeamSport': True},
            {'id': 'sport-21', 'name': 'Дворовые игры', 'isTeamSport': True},
            {'id': 'sport-22', 'name': 'Командный туризм и ориентирование', 'isTeamSport': True},
            {'id': 'sport-23', 'name': 'Гребля на лодках-драконах', 'isTeamSport': True},
            {'id': 'sport-24', 'name': 'Командные шахматы', 'isTeamSport': True},
            {'id': 'sport-25', 'name': 'Лёгкая атлетика', 'isTeamSport': False},
            {'id': 'sport-26', 'name': 'Плавание', 'isTeamSport': False},
            {'id': 'sport-27', 'name': 'Теннис', 'isTeamSport': False},
            {'id': 'sport-28', 'name': 'Бадминтон', 'isTeamSport': False},
            {'id': 'sport-29', 'name': 'Сквош', 'isTeamSport': False},
            {'id': 'sport-30', 'name': 'Единоборства', 'isTeamSport': False},
            {'id': 'sport-31', 'name': 'Фехтование', 'isTeamSport': False},
            {'id': 'sport-32', 'name': 'Стрельба', 'isTeamSport': False},
            {'id': 'sport-33', 'name': 'Тяжёлая атлетика', 'isTeamSport': False},
            {'id': 'sport-34', 'name': 'Пауэрлифтинг', 'isTeamSport': False},
            {'id': 'sport-35', 'name': 'Кроссфит', 'isTeamSport': False},
            {'id': 'sport-36', 'name': 'Гимнастика', 'isTeamSport': False},
            {'id': 'sport-37', 'name': 'Йога / стретчинг', 'isTeamSport': False},
            {'id': 'sport-38', 'name': 'Скалолазание', 'isTeamSport': False},
            {'id': 'sport-39', 'name': 'Серфинг / виндсёрфинг / кайтсёрфинг', 'isTeamSport': False},
            {'id': 'sport-40', 'name': 'Сноуборд / горные лыжи', 'isTeamSport': False},
            {'id': 'sport-41', 'name': 'Конный спорт', 'isTeamSport': False},
            {'id': 'sport-42', 'name': 'Велоспорт', 'isTeamSport': False},
            {'id': 'sport-43', 'name': 'Скейтбординг / роликовый спорт', 'isTeamSport': False},
            {'id': 'sport-44', 'name': 'Парашютный спорт', 'isTeamSport': False},
            {'id': 'sport-45', 'name': 'Парапланеризм', 'isTeamSport': False},
            {'id': 'sport-46', 'name': 'Триатлон', 'isTeamSport': False},
            {'id': 'sport-47', 'name': 'Гольф', 'isTeamSport': False},
            {'id': 'sport-48', 'name': 'Автоспорт / мотоспорт', 'isTeamSport': False},
            {'id': 'sport-49', 'name': 'Индивидуальные шахматы', 'isTeamSport': False},
            {'id': 'sport-50', 'name': 'Настольные игры как спорт', 'isTeamSport': False},
        ]
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('game', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prizePool', sa.String(length=100), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('maxParticipants', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('avatarUrl', sa.String(length=255), nullable=True),
    sa.Column('coverImageUrl', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('coach_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('experienceYears', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('player_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('matchesPlayed', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('referee_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('matchesJudged', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logoUrl', sa.String(length=200), nullable=True),
    sa.Column('captainId', sa.String(length=36), nullable=False),
    sa.Column('sportId', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('leagueRank', sa.String(length=50), nullable=True),
    sa.Column('currentStreakType', sa.String(length=1), nullable=True),
    sa.Column('currentStreakCount', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(length=5), nullable=True),
    sa.Column('mvpPlayerId', sa.String(length=36), nullable=True),
    sa.Column('topScorerPlayerId', sa.String(length=36), nullable=True),
    sa.Column('cleanSheets', sa.Integer(), nullable=True),
    sa.Column('avgRating', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['captainId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mvpPlayerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sportId'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['topScorerPlayerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('refreshToken', sa.String(length=512), nullable=False),
    sa.Column('userAgent', sa.String(length=255), nullable=True),
    sa.Column('ipAddress', sa.String(length=45), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lastActiveAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refreshToken'), ['refreshToken'], unique=False)

    op.create_table('user_sports',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('sportId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sportId'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'sportId')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_applications',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.create_table('team_followers',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.create_table('team_members',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('leagueRank', sa.String(length=50), nullable=True),
    sa.Column('finalElo', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('authorId', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('team_season_stats')
    op.drop_table('team_members')
    op.drop_table('team_followers')
    op.drop_table('team_applications')
    op.drop_table('post')
    op.drop_table('user_sports')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_refreshToken'))

    op.drop_table('user_sessions')
    op.drop_table('uploads')
    op.drop_table('team')
    op.drop_table('referee_profile')
    op.drop_table('player_profile')
    op.drop_table('coach_profile')
    op.drop_table('user')
    op.drop_table('tournament')
    op.execute('DELETE FROM sport')
    op.drop_table('sport')
    op.drop_table('sponsor')
    op.drop_table('quest')
    op.drop_table('playground')
    op.drop_table('achievement')
    # ### end Alembic commands ###
