"""Add coverImageUrl to User model

Revision ID: c3aa6c329875
Revises: 920804208d98
Create Date: 2025-10-31 20:21:13.518385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3aa6c329875'
down_revision = '920804208d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coverImageUrl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coverImageUrl')
    # ### end Alembic commands ###
