"""Manual migration for renaming user_disciplines, dropping subdiscipline
Revision ID: e317311a2802
Revises: d9c1084364c4
Create Date: 2025-10-31 17:29:20.632353
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'e317311a2802'
down_revision = 'd9c1084364c4'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS user_disciplines RENAME TO user_sports;")
    op.drop_table('subdiscipline')
    op.add_column('sport', sa.Column('parentId', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'sport', 'sport', ['parentId'], ['id'])
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS user_disciplines RENAME TO user_sports;")
    op.create_table('subdiscipline',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['sport.id'], name='subdiscipline_parentId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subdiscipline_pkey')
    )
    op.drop_column('sport', 'parentId')
    # ### end Alembic commands ###