"""Add unique constraint to subscriptions

Revision ID: eb882e4ea437
Revises: 321b43a582f9
Create Date: 2025-11-12 23:40:25.707327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb882e4ea437'
down_revision = '321b43a582f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
