"""initial

Revision ID: eca5698a21c5
Revises: 2a40cf1d78d4
Create Date: 2025-11-11 14:42:47.640216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca5698a21c5'
down_revision = '2a40cf1d78d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
