"""Rename user columns to snake_case and add birth_date

Revision ID: ed3c8389a694
Revises: 3770c1acf0db
Create Date: 2025-11-11 13:13:01.151546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed3c8389a694'
down_revision = '3770c1acf0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_profile', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('player_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('player_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('referee_profile', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('referee_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('referee_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_privacy_settings_user_id'), 'user_privacy_settings', ['user_id'])
    op.create_unique_constraint(op.f('uq_user_settings_user_id'), 'user_settings', ['user_id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=False))
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(op.f('uq_user_settings_user_id'), 'user_settings', type_='unique')
    op.drop_constraint(op.f('uq_user_privacy_settings_user_id'), 'user_privacy_settings', type_='unique')
    op.alter_column('referee_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('referee_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('referee_profile', 'id')
    op.alter_column('player_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('player_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('player_profile', 'id')
    # ### end Alembic commands ###
