"""Add team_followers table

Revision ID: fc93fb9c7ad5
Revises: 7dbdf531d788
Create Date: 2025-11-03 17:38:18.888489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc93fb9c7ad5'
down_revision = '7dbdf531d788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
